platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'Hamp' do

pod 'HampKit', :git => 'https://github.com/Hamp-tech/Hamp-iOS-Kit.git', :branch => 'features'
pod 'FacebookCore', :git => 'https://github.com/ulidev/facebook-sdk-swift.git'
pod 'FacebookLogin', :git => 'https://github.com/ulidev/facebook-sdk-swift.git'
pod 'Fabric'
pod 'Crashlytics'
pod 'InputMask'
pod 'RealmSwift'
pod 'Firebase/Messaging'
pod 'NVActivityIndicatorView'
end
